name: frontend
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <4.0.0"
dependencies:

  provider: ^6.0.4
  share_plus: 6.3.4
  carousel_slider: ^4.2.1
  photo_view: ^0.14.0
  flutter:
    sdk: flutter
  http: ^0.13.5
  flutter_html: ^3.0.0-alpha.5
  # flutter_markdown: ^0.6.14
  intl: ^0.18.0
  email_validator: ^2.1.17
  flutter_riverpod: ^2.4.0
  freezed_annotation: ^2.4.1
  dio: ^5.3.2
  cupertino_icons: ^1.0.2
  animated_bottom_navigation_bar: ^0.3.3
  flutter_vector_icons: ^2.0.0
  page_transition: ^2.0.5
  html2md: ^1.3.2
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  build_runner: ^2.4.6
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
