name: frontend
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  share_plus: ^7.2.1
  carousel_slider: ^4.2.1
  photo_view: ^0.14.0
  http: ^1.1.0
  flutter_html: ^3.0.0-beta.2
  intl: ^0.18.0
  email_validator: ^2.1.17
  flutter_riverpod: ^2.4.0
  freezed_annotation: ^2.4.1
  dio: ^5.3.2
  cupertino_icons: ^1.0.2
  animated_bottom_navigation_bar: ^0.3.3
  flutter_vector_icons: ^2.0.0
  page_transition: ^2.0.5
  html2md: ^1.3.2
  flutter_secure_storage: ^8.0.0
  # shared_preferences: ^2.3.3
  # shared_preferences_web: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/